hibernate:
  hbm2ddl:
    auto: update
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
teacher:
  vacationdays: '{''BACHELOR'': 10, ''DOCTOR'': 20, ''MASTER'': 30}'
  defaultsortattribute: id
group:
  maxstudents: '30'
defaultsortdirection: ASC
timeslot:
  minimumlength: '30'
  minimumbreaklength: '15'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university
    username: rector
    password: 1
student:
  defaultsortattribute: last_name
current_session_context_class: thread
