DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS classrooms;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS holidays;
DROP TABLE IF EXISTS lectures;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS vacations;
DROP TABLE IF EXISTS teachers_subjects;
DROP TABLE IF EXISTS teachers_vacations;
DROP TABLE IF EXISTS lessons_groups;
DROP TYPE IF EXISTS degree;
DROP TYPE IF EXISTS gender;

CREATE TYPE degree AS ENUM ('DOCTOR', 'BACHELOR', 'MASTER');
CREATE TYPE gender AS ENUM ('MALE','FEMALE');

CREATE TABLE addresses (
id integer NOT NULL generated BY DEFAULT AS identity,
country VARCHAR(255) NOT NULL,
postalCode VARCHAR(50) NOT NULL,
region VARCHAR(255),
city VARCHAR(255) NOT NULL,
streetAddress VARCHAR(255) NOT NULL
);

CREATE TABLE classrooms (
id integer NOT NULL generated BY DEFAULT AS identity,
location_id integer,
name VARCHAR(255),
capacity integer
);

CREATE TABLE locations (
id integer NOT NULL generated BY DEFAULT AS identity,
building VARCHAR(255),
floor integer,
room_number integer
);

CREATE TABLE groups (
id integer NOT NULL generated BY DEFAULT AS identity,
name VARCHAR(50)
);

CREATE TABLE holidays (
id integer NOT NULL generated BY DEFAULT AS identity,
date DATE,
name VARCHAR(255)
);

CREATE TABLE subjects (
id integer NOT NULL generated BY DEFAULT AS identity,
name VARCHAR(255),
description VARCHAR(255)
);

CREATE TABLE lectures (
id INTEGER NOT NULL generated BY DEFAULT AS identity,
date DATE,
begin_time TIME,
end_time TIME,
subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL,
teacher_id INTEGER REFERENCES teachers(id) ON DELETE SET NULL,
classroom_id INTEGER REFERENCES classrooms(id) ON DELETE SET NULL
);

CREATE TABLE students (
id integer NOT NULL generated BY DEFAULT AS identity,
first_name VARCHAR(255),
last_name VARCHAR(255),
gender GENDER,
birth_date DATE,
entry_year DATE,
email VARCHAR(255),
phone VARCHAR(255),
address_id INTEGER REFERENCES addresses(id) ON DELETE CASCADE
);

CREATE TABLE teachers (
id integer NOT NULL generated BY DEFAULT AS identity,
first_name VARCHAR(255),
last_name VARCHAR(255),
gender GENDER,
degree DEGREE,
email VARCHAR(255),
phone VARCHAR(255),
address_id INTEGER REFERENCES addresses(id) ON DELETE CASCADE
);

CREATE TABLE vacations (
id integer NOT NULL generated BY DEFAULT AS identity,
start_date DATE,
end_date DATE
);

CREATE TABLE teachers_subjects
(
id SERIAL PRIMARY KEY,
teacher_id INTEGER REFERENCES teachers(id) ON DELETE CASCADE,
subject_id INTEGER REFERENCES subjects(id) ON DELETE CASCADE
);

CREATE TABLE teachers_vacations
(
id SERIAL PRIMARY KEY,
teacher_id INTEGER REFERENCES teachers(id) ON DELETE CASCADE,
vacation_id INTEGER REFERENCES vacations(id) ON DELETE CASCADE
);

CREATE TABLE lectures_groups
(
id SERIAL PRIMARY KEY,
lesson_id INTEGER REFERENCES lectures(id) ON DELETE CASCADE,
group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE
);