package ua.com.foxminded.university.dao.jdbc.mappers;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Component;

import ua.com.foxminded.university.model.Address;

//CREATE TABLE addresses (
//id integer NOT NULL generated BY DEFAULT AS identity,
//country VARCHAR(255) NOT NULL,
//postalCode VARCHAR(50) NOT NULL,
//region VARCHAR(255),
//city VARCHAR(255) NOT NULL,
//streetAddress VARCHAR(255) NOT NULL,
//CONSTRAINT addresses_pkey PRIMARY KEY (id)
//);

@Component
public class AddressMapper implements RowMapper<Address> {

    @Override
    public Address mapRow(ResultSet rs, int rowNum) throws SQLException {
	Address address = new Address();
	address.setCountry(rs.getString("country"));
	address.setPostalCode(rs.getString("postalCode"));
	address.setRegion(rs.getString("region"));
	address.setCity(rs.getString("city"));
	address.setStreetAddress(rs.getString("streetAddress"));
	return address;
    }
}
