package ua.com.foxminded.university.dao.jdbc.mappers;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Component;

import ua.com.foxminded.university.model.Lecture;

//CREATE TABLE lectures (
//id INTEGER NOT NULL generated BY DEFAULT AS identity,
//date DATE,
//begin_time TIME,
//end_time TIME,
//subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL,
//teacher_id INTEGER REFERENCES teachers(id) ON DELETE SET NULL,
//classroom_id INTEGER REFERENCES classrooms(id) ON DELETE SET NULL,
//CONSTRAINT lectures_pkey PRIMARY KEY (id)
//);

@Component
public class LectureMapper implements RowMapper<Lecture> {

    @Override
    public Lecture mapRow(ResultSet rs, int rowNum) throws SQLException {
	Lecture lecture = new Lecture();
	lecture.setClassroom(null); // todo
	lecture.setDate(null); // todo
	lecture.setGroups(null); // todo
	lecture.setSubject(null); // todo
	lecture.setTeacher(null); // todo
	lecture.setTime(null); // todo
	return lecture;
    }

}
