package ua.com.foxminded.university.dao.jdbc.mappers;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Component;

import ua.com.foxminded.university.model.Student;

//CREATE TABLE students (
//id integer NOT NULL generated BY DEFAULT AS identity,
//first_name VARCHAR(255),
//last_name VARCHAR(255),
//gender GENDER,
//birth_date DATE,
//entry_year DATE,
//email VARCHAR(255),
//phone VARCHAR(255),
//address_id INTEGER REFERENCES addresses(id) ON DELETE CASCADE
//);

@Component
public class StudentMapper implements RowMapper<Student> {

    @Override
    public Student mapRow(ResultSet rs, int rowNum) throws SQLException {
	Student student = new Student();
	student.setAddress(null);
	student.setBirthDate(null);
	student.setEmail(null);
	student.setEntryYear(null);
	student.setFirstName(null);
	student.setPhoneNumber(null);
	student.setLastName(null);
	student.setGender(null);
	return student;
    }

}
