package ua.com.foxminded.university.dao.jdbc.mappers;

import java.sql.ResultSet;
import java.sql.SQLException;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Component;

import ua.com.foxminded.university.model.Teacher;

//CREATE TABLE teachers (
//id integer NOT NULL generated BY DEFAULT AS identity,
//first_name VARCHAR(255),
//last_name VARCHAR(255),
//gender GENDER,
//degree DEGREE,
//email VARCHAR(255),
//phone VARCHAR(255),
//address_id INTEGER REFERENCES addresses(id) ON DELETE CASCADE,
//CONSTRAINT teachers_pkey PRIMARY KEY (id)
//);

@Component
public class TeacherMapper implements RowMapper<Teacher> {

    @Override
    public Teacher mapRow(ResultSet rs, int rowNum) throws SQLException {
	Teacher teacher = new Teacher();
	teacher.setFirstName(null);
	teacher.setLastName(null);
	teacher.setGender(null);
	teacher.setDegree(null);
	teacher.setSubjects(null);
	teacher.setEmail(null);
	teacher.setPhoneNumber(null);
	teacher.setAddress(null);
	teacher.setVacations(null);
	return teacher;
    }

}
