package ua.com.foxminded.university.dao.jdbc.mappers;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.springframework.jdbc.core.RowMapper;
import org.springframework.stereotype.Component;

import ua.com.foxminded.university.model.Vacation;

//CREATE TABLE vacations (
//id integer NOT NULL generated BY DEFAULT AS identity,
//start_date DATE,
//end_date DATE,
//CONSTRAINT vacations_pkey PRIMARY KEY (id)
//);

@Component
public class VacationMapper implements RowMapper<Vacation> {

    @Override
    public Vacation mapRow(ResultSet rs, int rowNum) throws SQLException {
	Vacation vacation = new Vacation();
	vacation.setId(rs.getInt("id"));
	vacation.setStartDate(rs.getDate("start_date").toLocalDate());
	vacation.setEndDate(rs.getDate("end_date").toLocalDate());

	return vacation;
    }
}
