package ua.com.foxminded.university.dao.jdbc;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Component;

import ua.com.foxminded.university.dao.AddressDAO;
import ua.com.foxminded.university.dao.jdbc.mappers.AddressMapper;
import ua.com.foxminded.university.model.Address;

//CREATE TABLE addresses (
//id integer NOT NULL generated BY DEFAULT AS identity,
//country VARCHAR(255) NOT NULL,
//postalCode VARCHAR(50) NOT NULL,
//region VARCHAR(255),
//city VARCHAR(255) NOT NULL,
//streetAddress VARCHAR(255) NOT NULL,
//CONSTRAINT addresses_pkey PRIMARY KEY (id)
//);

@Component
public class JdbcAddressDAO implements AddressDAO {

    private static final String CREATE = "INSERT INTO addresses (country, postalcode, region, city, streetAddress) VALUES (?, ?, ?, ?, ?)";
    private static final String FIND_BY_ID = "SELECT * FROM addresses WHERE id = ?";
    private static final String FIND_ALL = "SELECT * FROM addresses";
    private static final String UPDATE_ = "UPDATE addresses SET name = ?, description = ? WHERE id = ?";
    private static final String DELETE_BY_ID = "DELETE FROM addresses WHERE id = ?";

    @Autowired
    private JdbcTemplate jdbcTemplate;
    @Autowired
    private AddressMapper addressMapper;

    public void addToDb(Address address) {
	KeyHolder keyHolder = new GeneratedKeyHolder();

	jdbcTemplate.update(connection -> {
	    PreparedStatement ps = connection
		    .prepareStatement(CREATE, Statement.RETURN_GENERATED_KEYS);
	    ps.setString(1, address.getCountry());
	    ps.setString(2, address.getPostalCode());
	    ps.setString(3, address.getRegion());
	    ps.setString(4, address.getCity());
	    ps.setString(5, address.getStreetAddress());
	    return ps;
	}, keyHolder);
	address.setId((int) keyHolder.getKeys().get("id"));
    }

    @Override
    public Optional<Address> findById(int id) {
	return Optional.of(jdbcTemplate.queryForObject(FIND_BY_ID, addressMapper, id));
    }

    @Override
    public List<Address> findAll() {
	return jdbcTemplate.query(FIND_ALL, addressMapper);
    }

    @Override
    public void update(Address e) {
	// TODO Auto-generated method stub

    }

    @Override
    public void delete(int id) {
	jdbcTemplate.update(DELETE_BY_ID, id);
    }

}
